[default_session]
command = "tuigreet --remember --remember-user-session --time \
--greeting 'Welcome' --cmd niri-session -l"
#--power-shutdown 'sudo systemctl poweroff' --power-reboot 'sudo systemctl reboot' \

[terminal]
vt = 7
